import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";
import { copyFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";

// Сборка идёт в корень проекта (main.js коммитится и попадает в релиз), копия
// кладётся в установленный плагин в хранилище. На CI хранилища нет —
// копирование пропускается. Если vault переедет, поправить этот один путь.
const VAULT_PLUGIN = "D:/Obsidian/mrrepac/.obsidian/plugins/ai-assist";

const copyToVault = {
  name: "copy-to-vault",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) return;
      if (!existsSync(VAULT_PLUGIN)) return; // CI: хранилища нет
      for (const f of ["main.js", "manifest.json", "styles.css", "versions.json"]) {
        copyFileSync(f, join(VAULT_PLUGIN, f));
      }
      console.log("→ vault");
    });
  },
};

const buildOptions = {
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", ...builtinModules, ...builtinModules.map((m) => `node:${m}`)],
  format: "cjs",
  target: "es2020",
  plugins: [copyToVault],
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
};

if (prod) {
  await esbuild.build(buildOptions);
} else {
  const ctx = await esbuild.context(buildOptions);
  await ctx.watch();
}
